### ISSUE TITLE
Adding null safety?

### ISSUE THREAD

**Issue by ahmedkamalio** [TheMisir/form-validator#16]
Any plan to support/migrate to null-safety?

**Comment by jonmountjoy** [comment]
I've added a PR for this: https://github.com/TheMisir/form-validator/pull/22

If you want to try this before it is merged, do something like this in your `pubspec.yaml`:

```
form_validator:
    git: 
      url: https://github.com/jonmountjoy/form-validator
      ref: null-support
```

**Comment by 2shrestha22** [comment]
Do this package support null safety in future?

**Comment by jonmountjoy** [comment]
See my PR https://github.com/TheMisir/form-validator/pull/22

While we wait for @TheMisir , you can try it before it's merged (or something similar) with something like this in your `pubspec.yaml`:

```
form_validator:
    git: 
      url: https://github.com/jonmountjoy/form-validator
      ref: null-support
```
